// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/account/service.proto

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountHandlerClient is the client API for AccountHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountHandlerClient interface {
	GetCurrentBalance(ctx context.Context, in *CurrentBalanceRequest, opts ...grpc.CallOption) (*CurrentBalanceResponse, error)
}

type accountHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountHandlerClient(cc grpc.ClientConnInterface) AccountHandlerClient {
	return &accountHandlerClient{cc}
}

func (c *accountHandlerClient) GetCurrentBalance(ctx context.Context, in *CurrentBalanceRequest, opts ...grpc.CallOption) (*CurrentBalanceResponse, error) {
	out := new(CurrentBalanceResponse)
	err := c.cc.Invoke(ctx, "/account.AccountHandler/GetCurrentBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountHandlerServer is the server API for AccountHandler service.
// All implementations must embed UnimplementedAccountHandlerServer
// for forward compatibility
type AccountHandlerServer interface {
	GetCurrentBalance(context.Context, *CurrentBalanceRequest) (*CurrentBalanceResponse, error)
	mustEmbedUnimplementedAccountHandlerServer()
}

// UnimplementedAccountHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedAccountHandlerServer struct {
}

func (UnimplementedAccountHandlerServer) GetCurrentBalance(context.Context, *CurrentBalanceRequest) (*CurrentBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentBalance not implemented")
}
func (UnimplementedAccountHandlerServer) mustEmbedUnimplementedAccountHandlerServer() {}

// UnsafeAccountHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountHandlerServer will
// result in compilation errors.
type UnsafeAccountHandlerServer interface {
	mustEmbedUnimplementedAccountHandlerServer()
}

func RegisterAccountHandlerServer(s grpc.ServiceRegistrar, srv AccountHandlerServer) {
	s.RegisterService(&AccountHandler_ServiceDesc, srv)
}

func _AccountHandler_GetCurrentBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CurrentBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountHandlerServer).GetCurrentBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountHandler/GetCurrentBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountHandlerServer).GetCurrentBalance(ctx, req.(*CurrentBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountHandler_ServiceDesc is the grpc.ServiceDesc for AccountHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountHandler",
	HandlerType: (*AccountHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentBalance",
			Handler:    _AccountHandler_GetCurrentBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account/service.proto",
}
