// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloHandlerrClient is the client API for HelloHandlerr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloHandlerrClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloHandlerrClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloHandlerrClient(cc grpc.ClientConnInterface) HelloHandlerrClient {
	return &helloHandlerrClient{cc}
}

func (c *helloHandlerrClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloHandlerr/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloHandlerrServer is the server API for HelloHandlerr service.
// All implementations must embed UnimplementedHelloHandlerrServer
// for forward compatibility
type HelloHandlerrServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHelloHandlerrServer()
}

// UnimplementedHelloHandlerrServer must be embedded to have forward compatible implementations.
type UnimplementedHelloHandlerrServer struct {
}

func (UnimplementedHelloHandlerrServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloHandlerrServer) mustEmbedUnimplementedHelloHandlerrServer() {}

// UnsafeHelloHandlerrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloHandlerrServer will
// result in compilation errors.
type UnsafeHelloHandlerrServer interface {
	mustEmbedUnimplementedHelloHandlerrServer()
}

func RegisterHelloHandlerrServer(s grpc.ServiceRegistrar, srv HelloHandlerrServer) {
	s.RegisterService(&HelloHandlerr_ServiceDesc, srv)
}

func _HelloHandlerr_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHandlerrServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloHandlerr/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHandlerrServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloHandlerr_ServiceDesc is the grpc.ServiceDesc for HelloHandlerr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloHandlerr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloHandlerr",
	HandlerType: (*HelloHandlerrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloHandlerr_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello/hello.proto",
}
