// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: proto/hello/hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloHandlerClient is the client API for HelloHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloHandlerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloHandlerClient(cc grpc.ClientConnInterface) HelloHandlerClient {
	return &helloHandlerClient{cc}
}

func (c *helloHandlerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/hello.HelloHandler/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloHandlerServer is the server API for HelloHandler service.
// All implementations must embed UnimplementedHelloHandlerServer
// for forward compatibility
type HelloHandlerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedHelloHandlerServer()
}

// UnimplementedHelloHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedHelloHandlerServer struct {
}

func (UnimplementedHelloHandlerServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloHandlerServer) mustEmbedUnimplementedHelloHandlerServer() {}

// UnsafeHelloHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloHandlerServer will
// result in compilation errors.
type UnsafeHelloHandlerServer interface {
	mustEmbedUnimplementedHelloHandlerServer()
}

func RegisterHelloHandlerServer(s grpc.ServiceRegistrar, srv HelloHandlerServer) {
	s.RegisterService(&HelloHandler_ServiceDesc, srv)
}

func _HelloHandler_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHandlerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.HelloHandler/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHandlerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloHandler_ServiceDesc is the grpc.ServiceDesc for HelloHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello.HelloHandler",
	HandlerType: (*HelloHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloHandler_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello/hello.proto",
}
